name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # 1️⃣ Checkout repo with submodules (needed for themes)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # 2️⃣ Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      # 3️⃣ Build Hugo site
      - name: Build Hugo
        run: hugo --minify --baseURL="https://Chan-McLaren.github.io/" 
        env:
          HUGO_ENV: produciton 

      # 4️⃣ Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
